version: "3"
networks:
  hyperledger:
    external:
      name: hyperledger
services:
  ca:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.hostname == peer1]
    hostname: ca.lorachain.io
    image: hyperledger/fabric-ca:x86_64-1.1.1
    networks:
      hyperledger:
        aliases:
        - ca_peerOrg1
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-org1
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.lorachain.io-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/40fdcbe0ab8446c547fed44f9da81462dd53e3e27a1d8b8ce5cb5df73b8adbc7_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.lorachain.io-cert.pem
      --ca.keyfile /etc/hyperledger/fabric-ca-server-config/40fdcbe0ab8446c547fed44f9da81462dd53e3e27a1d8b8ce5cb5df73b8adbc7_sk -b admin:adminpw
      -d'
    volumes:
    - ./crypto-config/peerOrganizations/org1.lorachain.io/ca/:/etc/hyperledger/fabric-ca-server-config

