version: "3"
networks:
  hyperledger-ov:
    external:
      name: hyperledger
services:
  couchdb0:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: couchdb0.lorachain.io
    image: hyperledger/fabric-couchdb:0.4.10
    networks:
      hyperledger-ov:
        aliases:
        - couchdb0
    
  couchdb1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: couchdb1.lorachain.io
    image: hyperledger/fabric-couchdb:0.4.10
    networks:
      hyperledger-ov:
        aliases:
        - couchdb1
  
  couchdb2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: couchdb2.lorachain.io
    image: hyperledger/fabric-couchdb:0.4.10
    networks:
      hyperledger-ov:
        aliases:
        - couchdb2
  
  couchdb3:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: couchdb3.lorachain.io
    image: hyperledger/fabric-couchdb:0.4.10
    networks:
      hyperledger-ov:
        aliases:
        - couchdb3
